#!/bin/bash

## #ddev-generated
## Description: Apache Solr control script
## Usage: solr
## Example: ddev solr

# This example runs inside the solr container.
# Note that this requires that /mnt/ddev_config be mounted
# into the solr container and of course that you have a container
# named solr.

/opt/solr/bin/solr $@
